var units = {
    "Vitamin A": "mcg",
    "Vitamin C": "mg",
    "Vitamin D": "mcg",
    "Vitamin E": "mg",
    "Vitamin K": "mcg",
    "Thiamin (B1)": "mg",
    "Riboflavin (B2)": "mg",
    "Niacin (B3)": "mg",
    "Pyridoxine (B6)": "mg",
    "Folate": "mcg",
    "Vitamin B12": "mcg",
    "Pantothenic Acid (B4)": "mg",
    "Calcium": "mg",
    "Chromium": "mcg",
    "Copper": "mcg",
    "Iron": "mg",
    "Magnesium": "mg",
    "Manganese": "mg",
    "Phosphorus": "mg",
    "Selenium": "mcg",
    "Zinc": "mg",
    "Potassium": "g",
    "Sodium": "g",
    "Protein": "g",
    "Carbohydrate": "g",
    "Fiber": "g",
    "Linoleic Acid": "g",
    "a-Linoleic Acid": "g",
    "Saturated Fat": "g",
    "Trans-Fat": "g",
    "Cholesterol": "mg"
}
this.units = units;